# This Dockerfile was generated by Rigel.
############################################################################

# Use an intermediate stage to clone external repositories without
# compromising the security of any private SSH key.
FROM ros:noetic as intermediate

RUN apt clean && apt update && apt install -y \
    git \
    python3-rosinstall \
    python3-vcstool \
    ssh

RUN mkdir -p /root/.ssh/

# Ensure hosts are accepted.
RUN touch /root/.ssh/known_hosts

RUN mkdir -p /ros_workspace/src

# Clone repositories from .repos or .rosinstall.
RUN cd /ros_workspace \ 
    && /bin/bash -c "source /opt/ros/noetic/setup.bash \
    " && echo

############################################################################

FROM ros:noetic-ros-core

# Install dependencies.
RUN rm -f /etc/apt/sources.list.d/ros*.list && \
    apt clean && apt update && apt install -y \
    build-essential \
    net-tools \
    python3-pip \
    python3-venv \
    curl \
    ssh \
    && rm -rf /var/lib/apt/lists/*

# Create default user 'rigeluser'.
ARG USERNAME=rigeluser
RUN groupadd $USERNAME
RUN useradd -ms /bin/bash -g $USERNAME $USERNAME

# Create ROS workspace folder
RUN mkdir -p /home/$USERNAME/ros_workspace/src

# Create virtual environment for Python dependencies
RUN python3 -m venv /home/$USERNAME/ros_workspace/.venv

# Set user as ROS workspace owner
RUN sh -c 'echo "$USERNAME ALL=(root) NOPASSWD:ALL" >> /etc/sudoers'
RUN sh -c 'sudo chown -R rigeluser:rigeluser /home/rigeluser'
USER $USERNAME

# Copy this repository into the ROS workspace.
COPY . /home/rigeluser/ros_workspace/src/rigel-orchestration-plugin

# Copy bringup script.
COPY dockerfile_entrypoint.sh /home/rigeluser/robot-entrypoint.sh

# Copy readiness probe script.
COPY readiness_probe.sh /usr/local/bin/readiness_probe.sh
RUN sudo chmod +x /usr/local/bin/readiness_probe.sh

# Compile ROS workspace.
RUN /bin/bash -c "source /opt/ros/noetic/setup.bash \ 
    && cd /home/rigeluser/ros_workspace \
    && catkin_make "
    
# Give permissions to user
RUN sh -c 'sudo chmod +x /home/rigeluser/robot-entrypoint.sh'
RUN sh -c 'sudo chown rigeluser:rigeluser /home/rigeluser/robot-entrypoint.sh'

# Launch ROS application.
CMD ["rostopic", "pub", "/hello", "std_msgs/String", "Hello from K8s", "-r", "1"]
ENTRYPOINT [ "/home/rigeluser/robot-entrypoint.sh" ]
